name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-and-newman:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vampi_image

    - name: Run Docker container
      run: |
        docker run \
        --detach \
        --name vampi \
        --publish 5000:5000 \
        vampi_image

    - name: List files
      run: |
        ls

    - name: Run authentication tests collection
      uses: matt-ball/newman-action@v2.0.0
      with:
        collection: VAmPI-LoginAndJwtToken-Tests-Collection.postman_collection.json
        environment: VamPI-Environment.postman_environment.json

    - name: Run integration tests collection
      uses: matt-ball/newman-action@v2.0.0
      with:
        collection: VAmPI-Tests-Collection.postman_collection.json
        environment: VamPI-Environment.postman_environment.json

    - name: Run authorization tests collection
      uses: matt-ball/newman-action@v2.0.0
      with:
        collection: VAmPI-Books-Authorization-Tests-Collection.postman_collection.json
        environment: VamPI-Environment.postman_environment.json

    - name: Run base tests collection
      uses: matt-ball/newman-action@v2.0.0
      with:
        collection: VAmPI-Tests-Collection.postman_collection.json
        environment: VamPI-Environment.postman_environment.json
