name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vampi_image

    - name: Run Docker container
      run: |
        docker run \
        --detach \
        --name vampi \
        --publish 5000:5000 \
        vampi_image

  newman:

      runs-on: ubuntu-latest
      needs: docker

      steps:
        - name: Newman Action
          uses: matt-ball/newman-action@v2.0.0
          with:
            collection: VAmPI-Tests-Collection.postman_collection.json
            environment: VamPI-Environment.postman_environment.json